name: uad-list-linter

on:
  pull_request:
    paths:
      - resources\assets\uad_lists.json
  push:
    paths:
      - resources\assets\uad_lists.json

jobs:
  syntax-and-typos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit
      env:
        SKIP: no-commit-to-branch
      run: pre-commit run --all-files

    - name: Check typos in data files
      uses: actions/check-diff-typo@v0.0.1
      with:
        token: ${{ secrets.PAT }}
        files: |
          resources\assets\uad_lists.json
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}